# Generated by Django 3.2.7 on 2022-12-29 12:05

from django.db import migrations

def create_default_plan(apps, schema_editor):
    Plan = apps.get_model('main', 'Plan')
    Plan.objects.create(
        plan_name='First Plan', 
        stripe_id='',
        price=99,
        time='month',
        valid='1 month')
    Plan.objects.create(
        plan_name='Second Plan', 
        stripe_id='',
        price=149,
        time='month',
        valid='2 month')
    Plan.objects.create(
        plan_name='First Plan', 
        stripe_id='',
        price=699,
        time='month',
        valid='3 month')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_plan)
    ]
